import type { MarketMover, FundamentalMetrics, MacroBackdrop, SocialSentiment } from '../types.js';

export const PUBLISHER_COMPLIANCE_DIRECTIVE = `
LEGAL COMPLIANCE & EDITORIAL DIRECTIVES (MANDATORY):
1. PUBLISHER'S EXEMPTION: This content is prepared solely for general educational and information purposes under the Publisher's Exemption of Section 202(a)(11)(D) of the U.S. Investment Advisers Act of 1940 and FINRA Rule 2210.
2. NO PERSONALIZED ADVICE: You MUST NOT offer personalized investment advice, price targets, buy/sell directives, or individual recommendations. Use impersonal, objective, analytical language (e.g., "The fundamental evidence suggests", "Market participants are weighing", "From a valuation multiple standpoint").
3. BALANCED EVIDENCE: You MUST present both an evidence-based Bull Case and Bear Case with equal empirical rigor.
4. FACTUAL INTEGRITY: You MUST ONLY cite numerical figures that match the provided ingested financial metrics. DO NOT invent revenue, P/E ratios, or margins.
5. NO AI DISCLOSURES OR CLAIMS: You MUST NEVER state or imply that this report or publication is generated by AI, artificial intelligence, LLMs, bots, prompts, or automated agents. Never include phrases such as "As an AI", "AI-generated", "synthesized by machine learning", etc. Present the analysis as an institutional equity research publication.
`;

export function buildSystemPrompt(): string {
  return `You are a Senior Quantitative Equity Research Analyst and AI Systems Architect. 
Your role is to produce rigorous, institutional-grade fundamental, macroeconomic, and valuation research reports on equities (including micro-cap and penny stocks) that moved significantly in today's trading session.

${PUBLISHER_COMPLIANCE_DIRECTIVE}

DETAILED REPORT STRUCTURE & ANALYTICAL DIRECTIVES:

1. Title & Executive Summary:
   - SEO-optimized title adhering to format: "[Company Name] ([Ticker]) [Surges|Drops] [X]%: Fundamental & Valuation Deep Dive"
   - Specify the precise Money Market Trading Venue (e.g. Nasdaq Capital Market, NYSE American, OTC Markets) and whether it is classified as a penny stock (< $5.00).
   - Executive summary explaining the catalyst, price movement, and volume divergence.

2. Trading Activity, Catalyst-Price Alignment & Artificial Inflation Analysis:
   - Analyze whether the equity is being artificially inflated by inspecting trading volume anomalies, relative volume (RVOL) vs 90-day averages, and social flow velocity.
   - Explicitly evaluate Catalyst-Price Divergence: assess whether the price action is ALIGNED with the news catalyst, or whether it exhibits DIVERGENT_SELL_THE_NEWS (priced to perfection, guidance fade), DIVERGENT_RELIEF_RALLY (cleared uncertainty, low bar exceeded), MACRO_DOMINATED (rates/sector contagion), or NOISE_SPECULATION (retail flow).
   - Synthesize the expectations vs. reality gap: explain why the market reacted this way relative to prior positioning and financial metrics.
   - Identify the major driver of the recent price action (e.g., retail social momentum, coordinated message-board hype, short-squeeze mechanics, algorithmic liquidity hunt, warrant hedging, clinical trial readout, or authentic institutional accumulation).
   - Provide a quantitative sentiment score (-1.0 to 1.0 or 0 to 100) and evaluate the real-world impact of financial news headlines and social media discussions (Twitter/X, StockTwits, Reddit) on the stock's order flow.

3. Balance Sheet & Solvency Stress Test (with Full Debt Breakdown):
   - Total debt, Debt-to-Equity ratio, and cash reserves.
   - Granular debt breakdown: Short-term debt vs. Long-term debt (maturities and liquidity drain).
   - Recent changes in debt obligations (new debt facilities, convertible notes, ATM dilution offerings, principal repayments).
   - Specific risks associated with the debt profile (refinancing costs in a high risk-free rate regime, restrictive covenants, insolvency or dilution risks).

4. Profitability, Operating Health & Historical Benchmarks:
   - Gross Margin, Operating Margin (EBIT), Return on Equity (ROE), Operating Cash Flow, and Free Cash Flow status.
   - Price-to-Book (P/B) ratio compared with industry average and 5-year historical median.
   - Price-to-Earnings (P/E) ratio compared with industry average and 5-year historical median.
   - 8-Quarter EPS progression: Review quarterly EPS over the past 2 years (8 quarters) to evaluate operational consistency and earnings surprises.

5. Management Quality, Competitive Moat & Core Qualitative Deep Dive:
   - Evaluate Management Quality & Track Record: Are experienced, proven managers in charge? Review their capital allocation discipline and historical execution.
   - Evaluate Competitive Moat: Moat rating (Wide, Narrow, None, Under Pressure) and durability (patents/IP, regulatory barriers, switching costs, cost advantages).
   - Thoroughly answer the 4 Key Company Questions:
     Q1: How does the company make money?
     Q2: Are its products or services in demand, and why?
     Q3: How has the company performed in the past?
     Q4: Is the company positioned for growth and profitability?
   - Thoroughly answer the 3 Key Industry Questions:
     Q1: How is the company's industry doing as a whole?
     Q2: What are the obstacles and challenges the company faces?
     Q3: Does the company face any economic, political, or cultural risks?

6. Multi-Model Valuation Engine:
   Evaluate the security across 8 recognized valuation methodologies:
   - Discounted Cash Flow (DCF): 10-year projected cash flows with explicit WACC and terminal growth rate.
   - Dividend Discount Model (DDM): Gordon Growth Model (or note why inapplicable for non-dividend payers).
   - Rapid Stock Valuation: Quick multiplier model (Rule of 72, Graham Number, or PEG benchmark).
   - Relative Valuation: Enterprise and equity multiples vs peer group medians (P/E, EV/EBITDA, P/S).
   - Residual Income Model (RIM): Book value plus discounted future residual earnings over the cost of equity.
   - Asset-Based Valuation: Net Asset Value (NAV) and liquidation floor assuming distressed asset haircuts.
   - Sector-Specific / Fleet / Asset Capacity Model: Sector tailored model (e.g. mining reserve NAV, airline available seat mile capacity, defense pipeline multiple).
   - Excess Return Model: Economic Value Added (EVA) spread (ROIC minus WACC multiplied by invested capital).
   - Synthesize a Consensus Fair Value and clear valuation verdict.

7. Objective Bull & Bear Theses with Cited Sources & Deduction Chains:
   - For every thesis point in BOTH the Bull Case and Bear Case:
     * Cite specific references and sources (SEC 10-K / 10-Q / 8-K filings, earnings calls, clinical trial data, industry reports, Federal Reserve macro releases) along with direct links to the resources.
     * Provide a clear, step-by-step deduction chain explaining exactly how those empirical facts boil down to the thesis conclusion.

8. Social Distribution Hooks & Publisher's Exemption Notice.

OUTPUT FORMAT:
You MUST respond with valid, parseable JSON conforming strictly to the requested schema. No conversational preamble.`;
}

export function buildUserPrompt(
  mover: MarketMover,
  fundamentals: FundamentalMetrics,
  macro: MacroBackdrop,
  sentiment: SocialSentiment
): string {
  const currentPB = typeof fundamentals.priceToBook === 'object' ? fundamentals.priceToBook?.current : fundamentals.priceToBook;
  const currentPE = typeof fundamentals.priceToEarnings === 'object' ? fundamentals.priceToEarnings?.current : fundamentals.peRatioTrailing;

  return `Generate an in-depth financial analysis report for the following equity:

=== MARKET MOVER DATA ===
Ticker: ${mover.ticker}
Company: ${mover.name}
Exchange: ${mover.exchange} (${mover.region})
Trading Venue: ${mover.moneyMarketTradingVenue} (Penny Stock Status: ${mover.isPennyStock ? 'YES (< $5.00)' : 'NO'})
Current Price: $${mover.price.toFixed(2)} (${mover.currency})
Session Move: ${mover.changePercent > 0 ? '+' : ''}${mover.changePercent.toFixed(2)}%
Volume: ${mover.volume.toLocaleString()} (Avg 3M: ${mover.avgVolume.toLocaleString()})
Category: ${mover.category.toUpperCase()}

=== INGESTED FUNDAMENTAL METRICS ===
Market Cap: $${(fundamentals.marketCap / 1e9).toFixed(2)}B
Classification: ${fundamentals.classification}
Fundamental Rating: ${fundamentals.fundamentalRating}
Trailing P/E: ${fundamentals.peRatioTrailing ?? currentPE ?? 'N/A'} (Industry Avg: ${fundamentals.priceToEarnings?.industryAverage ?? 'N/A'}, 5Y Avg: ${fundamentals.priceToEarnings?.historicalAverage5Y ?? 'N/A'})
Forward P/E: ${fundamentals.peRatioForward ?? 'N/A'}
PEG Ratio: ${fundamentals.pegRatio ?? 'N/A'}
Price / Book: ${currentPB ?? 'N/A'} (Industry Avg: ${fundamentals.priceToBook?.industryAverage ?? 'N/A'}, 5Y Avg: ${fundamentals.priceToBook?.historicalAverage5Y ?? 'N/A'})
EV / EBITDA: ${fundamentals.evToEbitda ?? 'N/A'}
Dividend Yield: ${fundamentals.dividendYield.toFixed(2)}%
Return on Equity (ROE): ${fundamentals.returnOnEquity.toFixed(1)}%
TTM Revenue: $${(fundamentals.revenueTTM / 1e9).toFixed(2)}B
TTM Net Income: $${(fundamentals.netIncomeTTM / 1e9).toFixed(2)}B
Gross Margin: ${fundamentals.grossMargin.toFixed(1)}%
Operating Margin: ${fundamentals.operatingMargin.toFixed(1)}%
Operating Cash Flow: $${(fundamentals.cashFlow.operatingCashFlow / 1e9).toFixed(2)}B
TTM Free Cash Flow: $${(fundamentals.freeCashFlowTTM / 1e9).toFixed(2)}B (Status: ${fundamentals.cashFlow.status})

=== DEBT STRUCTURE BREAKDOWN ===
Total Debt: $${(fundamentals.totalDebt / 1e9).toFixed(2)}B
Short-Term Debt: $${(fundamentals.shortTermDebt / 1e9).toFixed(2)}B
Long-Term Debt: $${(fundamentals.longTermDebt / 1e9).toFixed(2)}B
Short vs Long-Term Debt Ratio: ${fundamentals.shortVsLongTermRatio}
Recent Debt Changes: ${fundamentals.recentChangesInDebt}
Debt Risks: ${fundamentals.debtRisks}
Cash & Equivalents: $${(fundamentals.cashAndEquivalents / 1e9).toFixed(2)}B
Net Debt: $${(fundamentals.netDebt / 1e9).toFixed(2)}B
Debt to Equity: ${fundamentals.debtToEquity ?? 'N/A'}
Current Ratio: ${fundamentals.currentRatio ?? 'N/A'}
ROIC: ${fundamentals.roic ?? 'N/A'}%
Beta: ${fundamentals.beta ?? 1.0}
52-Week Range: $${fundamentals.fiftyTwoWeekLow.toFixed(2)} - $${fundamentals.fiftyTwoWeekHigh.toFixed(2)}

=== 8-QUARTER EPS PROGRESSION ===
Current TTM EPS: $${fundamentals.earningsPerShare.currentTTM.toFixed(2)}
Quarters History:
${fundamentals.earningsPerShare.quarterlyEPSPast2Years.map((q) => `- ${q.quarter}: $${q.eps.toFixed(2)} (${q.beat ? 'Beat' : 'Miss/In-Line'})`).join('\n')}

=== QUALITATIVE MOAT & MANAGEMENT ===
Management Quality Rating: ${fundamentals.managementQuality.rating}
Management Track Record: ${fundamentals.managementQuality.trackRecord}
Competitive Moat: ${fundamentals.competitiveMoat.rating}
Moat Summary: ${fundamentals.competitiveMoat.summary}
Company Revenue Model: ${fundamentals.companyQuestions.howCompanyMakesMoney}
Product Demand Driver: ${fundamentals.companyQuestions.productsDemandAndWhy}
Past Performance: ${fundamentals.companyQuestions.pastPerformanceSummary}
Growth & Profitability Outlook: ${fundamentals.companyQuestions.growthAndProfitabilityOutlook}
Industry Condition: ${fundamentals.industryQuestions.industryCondition}
Obstacles & Challenges: ${fundamentals.industryQuestions.obstaclesAndChallenges}
Macro/Political/Cultural Risks: ${fundamentals.industryQuestions.economicPoliticalCulturalRisks}

=== MULTI-MODEL VALUATIONS ===
Consensus Fair Value: $${fundamentals.valuationModels.consensusFairValue.toFixed(2)} (Verdict: ${fundamentals.valuationModels.verdict})
- DCF (10Y Cash Flow): $${(fundamentals.valuationModels.dcf.fairValue ?? fundamentals.valuationModels.dcf.intrinsicValue ?? 0).toFixed(2)} (${fundamentals.valuationModels.dcf.upside ?? fundamentals.valuationModels.dcf.upsidePercent ?? 0}%)
- Dividend Discount Model (DDM): $${(fundamentals.valuationModels.ddm.fairValue ?? fundamentals.valuationModels.ddm.intrinsicValue ?? 0).toFixed(2)} (${fundamentals.valuationModels.ddm.upside ?? fundamentals.valuationModels.ddm.upsidePercent ?? 0}%)
- Relative Multiples Valuation: $${(fundamentals.valuationModels.relativeValuation.fairValue ?? fundamentals.valuationModels.relativeValuation.intrinsicValue ?? 0).toFixed(2)} (${fundamentals.valuationModels.relativeValuation.upside ?? fundamentals.valuationModels.relativeValuation.upsidePercent ?? 0}%)
- Rapid PEG Model: $${(fundamentals.valuationModels.rapidStockValuation.fairValue ?? fundamentals.valuationModels.rapidStockValuation.intrinsicValue ?? 0).toFixed(2)} (${fundamentals.valuationModels.rapidStockValuation.upside ?? fundamentals.valuationModels.rapidStockValuation.upsidePercent ?? 0}%)
- Residual Income Model: $${(fundamentals.valuationModels.residualIncomeModel.fairValue ?? fundamentals.valuationModels.residualIncomeModel.intrinsicValue ?? 0).toFixed(2)} (${fundamentals.valuationModels.residualIncomeModel.upside ?? fundamentals.valuationModels.residualIncomeModel.upsidePercent ?? 0}%)
- Asset-Based Liquidation Floor: $${(fundamentals.valuationModels.assetBasedValuation.fairValue ?? fundamentals.valuationModels.assetBasedValuation.intrinsicValue ?? 0).toFixed(2)} (${fundamentals.valuationModels.assetBasedValuation.upside ?? fundamentals.valuationModels.assetBasedValuation.upsidePercent ?? 0}%)
- Excess Return Spread Model: $${(fundamentals.valuationModels.excessReturnModel.fairValue ?? fundamentals.valuationModels.excessReturnModel.intrinsicValue ?? 0).toFixed(2)} (${fundamentals.valuationModels.excessReturnModel.upside ?? fundamentals.valuationModels.excessReturnModel.upsidePercent ?? 0}%)
- Industry Specific Model: $${(fundamentals.valuationModels.industrySpecificModel.fairValue ?? fundamentals.valuationModels.industrySpecificModel.intrinsicValue ?? 0).toFixed(2)} (${fundamentals.valuationModels.industrySpecificModel.upside ?? fundamentals.valuationModels.industrySpecificModel.upsidePercent ?? 0}%)

=== MACROECONOMIC CONTEXT ===
US 10-Year Yield: ${macro.us10YearYield.toFixed(2)}%
US 2-Year Yield: ${macro.us2YearYield.toFixed(2)}%
Fed Funds Rate: ${macro.fedFundsRate.toFixed(2)}%
ECB Policy Rate: ${macro.ecbPolicyRate.toFixed(2)}%
VIX Volatility Index: ${macro.vixIndex.toFixed(2)}
WTI Crude Oil: $${macro.crudeOilWTI.toFixed(2)}/bbl
Macro Summary: ${macro.sectorImpactSummary}

=== SOCIAL SENTIMENT & FLOW ANOMALIES ===
Bullish Sentiment: ${sentiment.bullishPercent}%
Bearish Sentiment: ${sentiment.bearishPercent}%
Volume Anomaly Ratio: ${sentiment.volumeAnomalyRatio}x (vs 90d average)
Artificial Inflation Risk: ${sentiment.artificialInflationRisk} (Artificially Inflated: ${sentiment.isArtificiallyInflated})
Major Price Driver: ${sentiment.majorPriceDriver}
News Impact: ${sentiment.newsImpact}
Social Media Impact: ${sentiment.socialMediaImpact}
24h Discussion Delta: +${sentiment.volumeChange24h}%
Key Themes: ${sentiment.dominantThemes.join(', ')}

=== CATALYST DYNAMICS & EXPECTATIONS DIVERGENCE (TIER 1 INTELLIGENCE) ===
Catalyst-Price Alignment: ${sentiment.catalystAlignment || 'ALIGNED'}
${sentiment.catalystSynthesis ? `Expectations vs Reality Gap: ${sentiment.catalystSynthesis}` : ''}
${sentiment.filteredHeadlines && sentiment.filteredHeadlines.length > 0 ? `Verified Entity-Relevant Headlines (Relevance >= 6/10):\n${sentiment.filteredHeadlines.map((h) => `- [${h.source}] (${h.headlineSentiment}, Relevance: ${h.relevance}/10) ${h.title}`).join('\n')}` : ''}

=== WEB & COMMUNITY SCRAPED CATALYSTS ===
${sentiment.recentHeadlines && sentiment.recentHeadlines.length > 0 ? `Latest Financial News Headlines:\n${sentiment.recentHeadlines.map((h) => `- ${h}`).join('\n')}` : 'Latest Financial News: Standard market flow'}
${sentiment.sampleCatalysts && sentiment.sampleCatalysts.length > 0 ? `Community Discussion Samples:\n${sentiment.sampleCatalysts.map((c) => `- ${c}`).join('\n')}` : ''}
${sentiment.secFilingSummary ? `SEC EDGAR Regulatory Filing: ${sentiment.secFilingSummary}` : ''}

Please format your response strictly as JSON with this schema:
{
  "title": "string",
  "seoDescription": "string (150-160 chars)",
  "slug": "string (lowercase url slug, e.g. 'nvda-earnings-surge-valuation-analysis')",
  "primaryKeywords": ["keyword 1", "keyword 2", "keyword 3"],
  "secondaryKeywords": ["keyword 4", "keyword 5"],
  "catalystSummary": "string (concise 2-sentence summary of why it moved)",
  "catalystAlignment": "${sentiment.catalystAlignment || 'ALIGNED'}",
  "catalystSynthesis": "string (explicitly discuss market expectations vs. reality and catalyst divergence)",
  "markdownBody": "string (the complete markdown report with headings ##, markdown tables, and evidence)",
  "extractedFigures": {
    "peRatio": ${fundamentals.peRatioTrailing ?? fundamentals.peRatioForward ?? 0},
    "revenueTTM": ${fundamentals.revenueTTM},
    "operatingMargin": ${fundamentals.operatingMargin},
    "freeCashFlow": ${fundamentals.freeCashFlowTTM},
    "netDebt": ${fundamentals.netDebt},
    "movePercent": ${mover.changePercent}
  },
  "theses": {
    "bull": [
      { "point": "string", "sources": [{ "name": "string", "url": "https://..." }], "deductionChain": "string" }
    ],
    "bear": [
      { "point": "string", "sources": [{ "name": "string", "url": "https://..." }], "deductionChain": "string" }
    ]
  },
  "socialHooks": {
    "twitterThread": [
      "Tweet 1 (hook with ticker $${mover.ticker}, move, venue, and core finding)...",
      "Tweet 2 (fundamental metric breakdown with P/E and FCF)...",
      "Tweet 3 (macro context & valuation asymmetry, ending with link placeholder)..."
    ],
    "redditPost": {
      "title": "[Deep Dive] $${mover.ticker}: Fundamental Breakdown Following Today's ${mover.changePercent.toFixed(1)}% Move",
      "bodyMarkdown": "Comprehensive reddit markdown analysis with disclaimer...",
      "flair": "DD / Fundamental"
    },
    "telegramAlert": "🚨 **$${mover.ticker} Alert**: ${mover.name} moved ${mover.changePercent > 0 ? '+' : ''}${mover.changePercent.toFixed(1)}% today on ${mover.moneyMarketTradingVenue}. Key fundamental breakdown: ..."
  }
}`;
}
